[package]
name = "massa-sc-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", tag = "v0.4.3" }
anyhow = "1"
serde_json = "1"
rand = "0.8.4"
wyhash = "0.5.0"
base64 = "0"
serde = "1"
